package compiler

import (
	"fmt"
	"monkey/ast"
	"monkey/code"
	"monkey/object"
)

// Compiler represents the bytecode compiler.
type Compiler struct {
	instructions code.Instructions
	constants    []object.Object
}

// Bytecode represents instructions for our bytecode vm.
type Bytecode struct {
	Instructions code.Instructions // Instructions to execute
	Constants    []object.Object   // Constants to reference from the instructions by position number.
}

// New creates a new compiler instance.
//
// Returns:
//   - *Compiler: The new compiler instance.
func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []object.Object{},
	}
}

// Compile produces bytecode from our ast.
//
// Parameters:
//   - node: The root node of the program to compile.
//
// Returns:
//   - error: An error is returned when compilation fails.
func (c *Compiler) Compile(node ast.Node) error {
	switch node := node.(type) {
	case *ast.Program:
		for _, s := range node.Statements {
			err := c.Compile(s)
			if err != nil {
				return err
			}
		}

	case *ast.ExpressionStatement:
		err := c.Compile(node.Expression)
		if err != nil {
			return err
		}
		c.emit(code.OpPop)

	case *ast.InfixExpression:
		err := c.Compile(node.Left)
		if err != nil {
			return err
		}

		err = c.Compile(node.Right)
		if err != nil {
			return err
		}

		switch node.Operator {
		case "+":
			c.emit(code.OpAdd)
		case "-":
			c.emit(code.OpSub)
		case "*":
			c.emit(code.OpMul)
		case "/":
			c.emit(code.OpDiv)
		default:
			return fmt.Errorf("unknown operator %s", node.Operator)
		}

	case *ast.Boolean:
		if node.Value {
			c.emit(code.OpTrue)
		} else {
			c.emit(code.OpFalse)
		}

	case *ast.IntegerLiteral:
		integer := &object.Integer{Value: node.Value}
		c.emit(code.OpConstant, c.addConstant(integer))

	}
	return nil
}

// Bytecode outputs the bytecode generated by the compiler.
func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}

// addConstant appends a constant value to the end of the compiler's constants slice.
//
// Parameters:
//   - obj: the constant object to add the the compiler's constant slice.
//
// Returns:
//   - int: The index position of the newly added object.
func (c *Compiler) addConstant(obj object.Object) int {
	c.constants = append(c.constants, obj)
	return len(c.constants) - 1
}

// emit adds a new opcode and operands to the compiler instructions
//
// Parameters:
//   - op: The opcode instruction to add.
//   - operands: The operands to add to the instruction.
//
// Returns:
//   - int: Essentially a stack pointer to the start of the current instruction.
func (c *Compiler) emit(op code.Opcode, operands ...int) int {
	ins := code.Make(op, operands...)
	pos := c.addInstruction(ins)
	return pos
}

// addInstruction adds an instruction to the compiler and returns the start
// position for the new instruction.
//
// Parameters:
//   - ins: The instruction to add
//
// Returns:
//   - int: The starting position for the current instruction.
func (c *Compiler) addInstruction(ins []byte) int {
	posNewInstruction := len(c.instructions)
	c.instructions = append(c.instructions, ins...)
	return posNewInstruction
}
